project:
  type: website
  output-dir: docs

website:
  title: "Zichen Zhang"
  navbar:
    left:
      - text: "About You"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
